BudgetApp/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include

urlpatterns = [
    url(r'^', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'account'
urlpatterns = [
    url(r'^home', views.home, name='home'),
    url(r'^register', views.register , name = 'register'),
    url(r'^login',views.login_view , name= 'login'),
    url(r'^welcome', views.welcome , name='welcome'),
    url(r'^logout', views.logout_view , name = 'logout'),
    url(r'^expense_form',views.expense_form , name='expense_form'),
    url(r'^expenses' , views.expense_table , name='expense_table'),
    url(r'^incomes', views.income_table , name= 'income_table'),
    url(r'^income_form', views.income_form, name='income_form'),
    url(r'^total', views.total, name = 'total'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser , User
from datetime import datetime

# Create your models here.

class categoryManager(models.Manager):
    def get_by_natural_key(self , name):
        return self.get(name=name)

class Category(models.Model):
    MY_CHOICES = (
        ('I', 'Income'),
        ('E', 'Expense'),
    )
    name = models.CharField(max_length=50)
    required = models.BooleanField(default=True)
    type = models.CharField(max_length=1 , choices=MY_CHOICES , null=True)
    object = categoryManager()
    def __str__(self):
        return self.name

    def natural_key(self):
        return self.name

class Incomes(models.Model):
    name = models.CharField(max_length=100)
    place = models.CharField(max_length=100, blank= True)
    price = models.DecimalField(decimal_places=2 , max_digits=20)
    date = models.DateField('date')
    category = models.ForeignKey(Category, on_delete = models.DO_NOTHING , blank = True , db_constraint=False , null=True, limit_choices_to={'type':'I'})
    user = models.ForeignKey(User, on_delete= models.CASCADE , blank=False)

    def __str__(self):
        final_string = "you spent" + str(self.price) + "at" + self.name
        return final_string


class Expense(models.Model):
    name = models.CharField(max_length=100)
    place = models.CharField(max_length=100, blank=True)
    price = models.DecimalField(decimal_places=2 , max_digits=20)
    date = models.DateField('date')
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING , blank= True , null=True, db_constraint=False , limit_choices_to={'type':'E'})
    user = models.ForeignKey(User, on_delete= models.CASCADE , blank= False)

    def __str__(self):
        final_string = "you spent" + str(self.price) + "at" + self.name
        return final_string

accounts/forms.py
from .models import User,Expense,Incomes,Category
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms

class SignInForm(UserCreationForm):
    email = forms.EmailField(max_length=254, required=False)
    class Meta:
        model = User
        fields = ('username','email', 'password1', 'password2',)

class loginForm(forms.Form):
    username = forms.CharField(label='username', max_length=100)
    password = forms.CharField(label='password', widget=forms.PasswordInput())


class Expense_form(ModelForm):
    class Meta:
        model = Expense
        exclude = ('user',)
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'})
        }

class Income_form(ModelForm):
    class Meta:
        model = Incomes
        exclude = ('user',)
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'})
        }

accounts/views.py
from django.shortcuts import render , redirect , render_to_response
import json
from datetime import datetime
from django.http import HttpResponse, JsonResponse
from .forms import loginForm , SignInForm , Expense_form, Income_form
from django.contrib.auth import authenticate , login , logout
from .models import User , Expense , Incomes
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
# Create your views here.

def home(request):
    return render(request, 'accounts/home.html')

def register(request):
    form = SignInForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            print("user is saved")
            username = form.cleaned_data.get('username')
            name = form.cleaned_data.get('first_name')
            return redirect("account:home")
    else:
        return render(request, 'accounts/login_page.html', {'form': form})

def login_view(request):
    form =  loginForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            usera = authenticate(request, username = username , password = password)
            if usera is not None:
                login(request, usera)
                return redirect('account:total')
            else:
                return HttpResponse("the user did not exist")
        else:
            return HttpResponse("the form is not valid ")
    else:
        return render(request,'accounts/login_page.html', {'form': form})


def logout_view(request):
    user = request.session
    try:
        logout(request)
    except:
        return HttpResponse("user doesnt exist to logout")
    return render(request , "accounts/home.html")


def welcome(request):
    if request.user.is_authenticated:
        return total(request)
    else:
        return redirect('account:login')

def total(request):
    if request.is_ajax():
        form_value = request.POST.get('month')
        form_value = form_value.split('-')
        month = form_value[1]
        year = form_value[0]
        e_table = Expense.objects.filter(user=request.user, date__month=month, date__year=year)
        i_table = Incomes.objects.filter(user=request.user, date__month=month, date__year=year)
        e_total = float(0)  # total for the users expenses for the month
        for item in e_table:
            e_total += float(item.price)
        e_total = round(e_total, 2)
        i_total = float(0)  # total for the users incomes for the month
        for item in i_table:
            i_total += float(item.price)
        i_total = round(i_total, 2)
        ie_total = i_total - e_total
        data = {
            'total': ie_total
        }
        category_expense_totals = {}
        for item in e_table:
            if str(item.category) not in category_expense_totals:
                category_expense_totals[str(item.category)] = float(item.price)
            else:
                category_expense_totals[str(item.category)] += float(item.price)

        sent_json = json.dumps({'total':ie_total,'category_expense_table':category_expense_totals})
        return HttpResponse(sent_json, content_type='application/JSON')

    else:
        today = datetime.today()
        month = today.month
        year = today.year
        e_table = Expense.objects.filter(user = request.user ,date__month= month , date__year=year)
        i_table = Incomes.objects.filter(user = request.user, date__month= month, date__year=year)
        e_total = float(0) #total for the users expenses for the month
        for item in e_table:
            e_total += float(item.price)
        e_total = round(e_total, 2)
        i_total = float(0) #total for the users incomes for the month
        for item in i_table:
            i_total += float(item.price)
        i_total = round(i_total, 2)
        ie_total = i_total - e_total
        ie_total = round(ie_total,2)
        if (month % 10) == 0: #look over this code one more time
            month_year = str(year)+"-"+str(month)
        else:
            month_year = str(year) + "-0" + str(month) # to set the value the month needs to be in YYYY-MM format

        category_expense_totals = {}
        for item in e_table:
            if str(item.category) not in category_expense_totals:
                category_expense_totals[str(item.category)] = float(item.price)
            else:
                category_expense_totals[str(item.category)] += float(item.price)
        category_expense_totals = json.dumps(category_expense_totals)
        print(category_expense_totals)
        return render(request, 'accounts/total.html', {'total':ie_total , 'month_year':month_year , 'cat_expense_total':category_expense_totals})




def expense_form(request):
    form = Expense_form(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            expense_temp_form = form.save(commit=False)
            expense_temp_form.user = request.user
            form.save()
            return redirect('account:expense_table')
        else:
            return HttpResponse("form was not valid")
    else:
        return render(request,'accounts/login_page.html',{'form':form})

def income_form(request):
    form = Income_form(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            income_temp_form = form.save(commit=False)
            income_temp_form.user = request.user
            form.save()
            return redirect('account:income_table')
        else:
            return HttpResponse("form was not valid")
    else:
        return render(request , 'accounts/login_page.html',{'form':form})


def expense_table(request):
        if request.method == 'GET':
            today = datetime.now()
            month = today.month
            year = today.year
            tables = Expense.objects.filter(user = request.user ,date__month= month , date__year=year)
            total = float(0)
            for item in tables:
                total += float(item.price)
            total = round(total, 2)
            page = 'expense'
            return render(request , 'accounts/tab_content.html' , {'tables':tables , 'page':page , 'total':total})
        else:
            if request.is_ajax():
                form_value = request.POST.get('month')
                form_value = form_value.split('-')
                month = form_value[1]
                year = form_value[0]
                tables = Expense.objects.filter(user=request.user, date__month=month, date__year=year)
                serialized_data = serializers.serialize('json',tables,indent=2,use_natural_foreign_keys=True, use_natural_primary_keys=True)
                return HttpResponse(serialized_data,content_type='application/json')

def income_table(request):
    if request.method == 'GET':
        today = datetime.now()
        month = today.month
        year = today.year
        tables = Incomes.objects.filter(user = request.user , date__month = month , date__year=year)
        total = float(0)
        for item in tables:
            total += float(item.price)
        total = round(total , 2)
        page = 'income'
        return render(request,'accounts/tab_content.html', {'tables':tables , 'page':page , 'total':total})
    else:
        if request.is_ajax():
            form_value = request.POST.get('month')
            form_value = form_value.split('-')
            month = form_value[1]
            year = form_value[0]
            tables = Incomes.objects.filter(user=request.user, date__month=month, date__year=year)
            serialized_data = serializers.serialize('json', tables, indent=2, use_natural_foreign_keys=True,
                                                    use_natural_primary_keys=True)
            return HttpResponse(serialized_data, content_type='application/json')

templates/accounts/Content.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <link href="{% static "/accounts/styles.css" %}", rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lexend+Deca&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans|Oswald:500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static 'accounts/jscript/filter_date.js' %}"></script>
    <link href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css" rel="stylesheet">
    <script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">
    <script src="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>
    <script type="text/javascript" src="https://cdn.fusioncharts.com/fusioncharts/latest/fusioncharts.js"></script>
    <!-- jQuery-FusionCharts -->
    <script type="text/javascript" src="https://rawgit.com/fusioncharts/fusioncharts-jquery-plugin/develop/dist/fusioncharts.jqueryplugin.min.js"></script>
    <!-- Fusion Theme -->
    <script type="text/javascript" src="https://cdn.fusioncharts.com/fusioncharts/latest/themes/fusioncharts.theme.fusion.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
</head>
<body>
    <nav class = "navbar sticky-top" style="background-color: #303942 ; padding: 0px; opacity: 1 ; border-radius: 8px">
            <a class="navbar-brand" href="#">
                <span class="navbar-brand mb-0 h-100 p-0" style="color: #f9f9f9">Fore$ight</span>
            </a>
            <a class="nav-item nav-link active m-0 p-0" href="{% url 'account:total' %} " style="padding-left: 10px; color: #f9f9f9;font-family: 'Josefin Sans' , sans-serif">Total</a>
            <a class="nav-item nav-link active " href="{% url 'account:expense_table' %}" style="padding-left: 10px; color: #f9f9f9;font-family: 'Josefin Sans' , sans-serif">Expenses</a>
            <a class="nav-item nav-link active" href="{% url 'account:income_table' %}" style="padding-left: 10px; color: #f9f9f9;font-family: 'Josefin Sans' , sans-serif">Incomes</a>
            <a class="nav-item nav-link active" href="#" style="padding-left: 10px; color: #f9f9f9;font-family: 'Josefin Sans' , sans-serif">Profile</a>
            <a class="nav-item nav-link active" href="{% url 'account:logout' %}" style="padding-left: 10px; color: #f9f9f9;font-family: 'Josefin Sans' , sans-serif">Logout</a>
    </nav>
{% block content %}

{% endblock %}
</body>
{% block scripts %}

{% endblock %}
</html>

templates/accounts/home.html
{% extends 'base.html' %}
{% load static %}
{% block head  %}
<title>Fore$ight home</title>
{% endblock %}

{% block content %}
  <div class="container h-100">
    <div class = "row h-70 justify-content-center align-items-center">
        <img src="{% static "accounts/recent_logo.png"%}" height="500px" width="500px" style="padding-top: 50px">
    </div>
    <div class = "row justify-content-center">
        <div class = "col-md-3">
            <a href= {% url 'account:login' %}>
            <button type = button  class="btn btn-secondary" style="min-width: 100px; font-family: 'Josefin Sans' , sans-serif; background-color: #343434">existing user</button>
            </a>
            <a href= {% url 'account:register' %}>
            <button type = button class="btn btn-secondary"  style="min-width: 120px; font-family:'Josefin Sans' , sans-serif; background-color: #343434" >create user</button>
            </a>
        </div>
    </div>
  </div>

{% endblock %}

templates/accounts/login_page.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans|Oswald:500&display=swap" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="container h-100">
    <div class = "row justify-content-center align-items-center">
        <img src="{% static "accounts/recent_logo.png"%}" style="width: 300px;height: 300px">
        <div class = "col-md-11 h-75" >
            <form method="post" class = empty-form>
                {% csrf_token %}
                {{  form.as_p }}
                <button type="submit" class="btn btn-secondary">Submit</button>
            </form>
        </div>
{% endblock %}

templates/accounts/tab_content.html
{% extends 'accounts/Content.html' %}
{% load static%}
{% block content %}
   <div class="container-fluid h-100 w-80 pt-0" style="background-color: #f9f9f9; opacity: .8" id="other">
        <div class="row justify-content-center pt-3 pb-0" style="opacity: 1">
                <img src="{% static "accounts/logo_navbar_burned.png"%}" height="100px" width="100px">
        </div>
        <div class="row justify-content-center p-0 m-0">
            <div class="jumbotron jumbotron-fluid pt-3 pb-0" style="background-color: #f9f9f9; border-color: #f9f9f9">
                <div id="big">
                    <h1 id="big_number "class="display-2" style="font-family: 'Lexend Deca', sans-serif;" >$ {{ total }}</h1>
                </div>
            </div>
        </div>
       <div class = "row m-0 p-0">
           {%  if page == 'expense' %}
               <a href="{% url 'account:expense_form' %}">
                   <button class="btn" style="width: 100px;height: 40px; background-color:#303942; font-family: 'Josefin Sans' , sans-serif; color: #f9f9f9; border-radius: 5px" >Add new</button>
               </a>
           {% endif %}
           {% if page == 'income' %}
                <a href="{% url 'account:income_form' %}">
                    <button class="btn" style="width: 100px;height: 40px; background-color:#303942; font-family: 'Josefin Sans' , sans-serif; color: #f9f9f9;" >Add new</button>
                </a>
           {% endif %}
           <div class="card w-100" style="border-radius: 0px;">
             <table class="table" id="user_table">
                <thead class = "thead-dark" style="color: #343434 ; font-family: 'Josefin Sans' , sans-serif ; border-radius: 0px">
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Place</th>
                            <th scope="col">Price</th>
                            <th scope="col">Date      <input type="month" id="user_input" name="datepicker" style="width:275px" onchange="userinput()"></th>
                            <th scope="col">Category</th>
                        </tr>
                </thead>
                <tbody id="user_table_body" style="font-family: 'Josefin Sans' , sans-serif">
                    {% for item in tables %}
                        <tr>
                            <td style="font-family: 'Josefin Sans' , sans-serif">{{ item.name }}</td>
                            <td style="font-family: 'Josefin Sans' , sans-serif">{{ item.place }}</td>
                            <td style="font-family: 'Josefin Sans' , sans-serif">{{ item.price }}</td>
                            <td style="font-family: 'Josefin Sans' , sans-serif">{{ item.date }}</td>
                            <td style="font-family: 'Josefin Sans' , sans-serif">{{ item.category }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
             </table>
            </div>
       </div>
   </div>
{% endblock %}
{% block scripts %}
    <script>
        var token = '{% csrf_token %}';
       function userinput() {
           const date = document.getElementById('user_input');
           var month_year = date.value
           console.log(month_year)
            $.ajax({
                headers: { "X-CSRFToken": '{{csrf_token}}'},
                method: "POST",
                {% if page == 'expense'%}
                    url: 'expenses',
                {% else %}
                    url: 'incomes',
                {% endif %}
                data: {
                    'month': month_year
                },

                dataType: 'json',
                success: function (data) {
                    $("#user_table_body").find("tr").remove()
                    var table = document.getElementById("user_table")
                    var total =  0
                    var new_rows;
                    for (item in data) {
                        console.log(data[item]['fields']);
                        string_date = convert_string_date(data[item]['fields']['date']);
                        new_rows = "<tr><td>" + data[item]['fields']['name'] + "</td><td>" + data[item]['fields']['place'] + "</td><td>" + data[item]['fields']['price'] + "</td><td>" + string_date + "</td><td>" + data[item]['fields']['category'] + "</td></tr>"
                        $('#user_table_body').append(new_rows);
                        total += parseFloat(data[item]['fields']['price']);
                    }
                    total = total.toFixed(2);
                    var replaced_string = "<div id=\"big\"> <h1 id=\"big_number \"class=\"display-2\" style=\"font-family: 'Lexend Deca', sans-serif;\" >$ "+ total +"  </h1></div>"
                    $("#big").replaceWith(replaced_string);
                }
            })}

            function convert_string_date(date){ //changes string data to the one used in the template
                given_date = date.split("-");
                month = given_date[1];
                a = {
                    '01':"Jan",
                    '02':"Feb",
                    "03":"Mar",
                    "04":"Apr",
                    "05":"May",
                    "06":"Jun",
                    "07":"Jul",
                    "08":"Aug",
                    "09":"Sep",
                    "10":"Oct",
                    "11":"Nov",
                    "12":"Dec"
                };
                string_month = a[month];
                year = given_date[0];
                day= given_date[2];
                return string_month+". "+day+", "+year;
            }
           </script>
{% endblock %}

templates/accounts/total.html
{% extends 'accounts/Content.html' %}
{% load static %}
{% block content %}
    <div class="container-fluid h-100 w-80 pt-0" style="background-color: #f9f9f9; opacity: .8" id="other">
        <div class="row justify-content-center pt-3">
            <img src="{% static "accounts/logo_navbar_burned.png"%}" height="100px" width="100px">
        </div>
        <div class="row justify-content-center">
            <div class="jumbotron jumbotron-fluid pt-3 pb-0 pr-5" style="background-color: #f9f9f9; border-color: #f9f9f9">
                <div id="big">
                    <h1 id="big_number "class="display-1" style="font-family: 'Lexend Deca', sans-serif;" >$ {{ total }}</h1>
                </div>
             </div>
        </div>
        <div class="row justify-content-center">
            <div class="mdc-text-field mdc-text-field--outlined">
              <input type= "month" class="mdc-text-field__input" id="month_value" value="{{ month_year }}" onchange="userinput()">
              <div class="mdc-notched-outline">
                <div class="mdc-notched-outline__leading"></div>
                <div class="mdc-notched-outline__notch">
                </div>
                <div class="mdc-notched-outline__trailing"></div>
              </div>
            </div>
        </div>
        <div class="row h-50 w-50 pt-3" style="background: #f9f9f9">
            <div class="col">
                 <div id="chart-container" style="background: transparent !important; opacity: 1;  border: 2px solid black; border-radius: 5px ;"></div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
    var token = '{% csrf_token %}';
    function userinput(){
        const date = document.getElementById("month_value");
        var month_year = date.value
        console.log('worked boi')
        $.ajax({
            headers: { "X-CSRFToken": '{{csrf_token}}'},
            method: "POST",
            url: 'total',
            data:{
                'month' : month_year
            },
            dataType:'json',
            success: function (data){
                console.log(data);
                console.log(data['total']);
                console.log(data['category_expense_table'])
                data_set = []
                for(item in data['category_expense_table']){
                    var temp_dict = {"label":item,"value":data['category_expense_table'][item]};
                    data_set.push(temp_dict)
                }
            $("#chart-container").insertFusionCharts({
              type: "pie2d",
              width: "100%",
              height: "100%",
              dataFormat: "json",
              dataSource: {
                chart: {
                  caption: "Expenses For This Month",
                  plottooltext: "<b>$Value</b> Dollars spent on $label",
                  showlegend: "1",
                  showpercentvalues: "1",
                  legendposition: "bottom",
                  usedataplotcolorforlabels: "1",
                  theme: "fusion",
                  chartleftmargin:"10px",
                  chartrightmargin:"10px",
                },
                data: data_set

            }
        });



                value_to_replace = parseFloat(data['total']);
                total = value_to_replace.toFixed(2)
                replaced_string = "<div id=\"big\"> <h1 id=\"big_number \"class=\"display-2\" style=\"font-family: 'Lexend Deca', sans-serif;\" >$ "+ total +"  </h1></div>"
                $('#big').replaceWith(replaced_string);


            }
        })
    }
    </script>
    <script type="text/javascript">
    console.log({{cat_expense_total|safe}});
    var json = JSON.parse('{{ cat_expense_total|safe }}');
    data_set = []
    for(item in json){
        var temp_dict = {"label":item,"value":json[item]};
        data_set.push(temp_dict)
    }
    $("#chart-container").insertFusionCharts({
      type: "pie2d",
      width: "100%",
      height: "100%",
      dataFormat: "json",
      dataSource: {
        chart: {
          caption: "Expenses For This Month",
          plottooltext: "<b>$Value</b> Dollars spent on $label",
          showlegend: "1",
          showpercentvalues: "1",
          legendposition: "bottom",
          usedataplotcolorforlabels: "1",
          theme: "fusion",
          chartleftmargin:"10px",
            chartrightmargin:"10px",
        },
        data: data_set
      }
});
    </script>
{% endblock %}